### ISSUE TITLE
Could you please kindly share the parameters used in T-SNE?

### ISSUE THREAD

**Issue by mitming** [LeiLiu-byte/the-Essence-of-LT-Rocognition#1]
Hi @LeiLiu-byte , thanks for your contribution, I tried to reproduce the T-SNE results reported in your paper, but failed, could you please share the parameters used? and which T-SNE library is used?

And when can you release the Appendix?

**Comment by LeiLiu-byte** [comment]
Thanks for your attention. I will release the appendix after the results of NeuIPS. I have shared the tsne code by email.

**Comment by LeiLiu-byte** [comment]
> Hi @LeiLiu-byte , thanks for your contribution, I tried to reproduce the T-SNE results reported in your paper, but failed, could you please share the parameters used? and which T-SNE library is used?
> 
> And when can you release the Appendix?

Thanks for your attention. I will release the appendix after the results of NeurIPS. I have shared the tsne code by email.

**Comment by mitming** [comment]
Thanks a lot
